### PR TITLE
[Fixed JENKINS-28722] Integrate Build-Failure-Analyzer Plugin with Cl…

### PR DESCRIPTION
**Pull request by toericliou**
…aim plugin

---
Given a failed build and Build-Failure-Analyzer is installed, the user is presented with
the defined failure causes in the BFA knowledgebase upon claiming. If a failure cause is selected,
the indication is stored by BFA.

-Add ClaimBuildFailureAnalyzer to allow claiming of failure causes
-Add dynamic dropdown box + text-field on UI to display failure causes
-Implement tests to verify new functionality

See JENKINS-28722

### CODE REVIEW

**Comment by ki82** [comment]
Will try to make a release of new version of claim during next week.

**Comment by toericliou** [comment]
Any estimate on what day you'll release?

**Comment by scoheb** [comment]
Hi,

Do you think you'll be able to make a release with the functionality soon?

**Comment by ki82** [comment]
Hi,
I have a new computer and tried to release on that but for some reason some of the test fails for me locally with port conflicts. Looked at it briefly and did not understand why and have not have the time to dig deeper yet.

**Comment by ki82** [comment]
@scoheb @toericliou 2.8 is now release, sorry for the delay.

**Pull request merged**
