### PR TITLE
[FIXED JENKINS-33715] Fix Class Cast Exception when claiming Test

### PR DESCRIPTION
**Pull request by wolfs**

### CODE REVIEW

**Comment by sthirugn** [comment]
I just commented on the main issue - https://issues.jenkins-ci.org/browse/JENKINS-33715?focusedCommentId=254952&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-254952.  I am curious if this PR will fix this issue?

**Comment by sthirugn** [comment]
I request to kindly review/merge this PR.  We are blocked with this issue.

**Comment by rplevka** [comment]
+1

**Comment by sthirugn** [comment]
Thank you so much @ki82.  Do you know when the plugins get refreshed with the new code.  I am new to this project and not sure about the workflow. Any inputs is greatly appreciated.

**Pull request merged**
